### ISSUE TITLE
convert MARC to PNX

### ISSUE THREAD

**Issue by ckrempe** [LibreCat/Catmandu-PNX#1]
I'm trying to convert a MARCXML file 
[ck_neu.docx](https://github.com/LibreCat/Catmandu-PNX/files/793969/ck_neu.docx)

to PNX: 
catmandu convert MARC --format XML to PNX < ck_neu.xml

As result I get:
```
<?xml version="1.0"  encoding="UTF-8"?>
<OAI-PMH xmlns="http://www.openarchives.org/OAI/2.0/"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="
        http://www.openarchives.org/OAI/2.0/  http://www.openarchives.org/OAI/2.0/OAI-PMH.xsd">
<ListRecords>
<record>
<header>
<identifier>undefined</identifier>
</header>
<metadata>
mistake: unused tags _id record at record
<record>
  <control/>
</record>
</metadata>
</record>
</ListRecords>
</OAI-PMH>
```

Are there any parameters missing?

**Comment by jorol** [comment]
A direct conversion from MARC to PNX is not possible, you have to create a `fix` to map the MARC fields to PNX record elements. For a simple example how to map MARC fields see <https://librecatproject.wordpress.com/2014/12/11/day-9-processing-marc-with-catmandu/>. You can find a more detailed documentation for  `fixes`  here <http://librecat.org/Catmandu/#fixes-cheat-sheet>.

**Comment by jorol** [comment]
A simple example:

Create `fix` file `marc2pnx.fix`

```
marc_map(001,control.sourcerecordid)
marc_map(245ab,display.title,-join: " ")
remove_field(_id)
remove_field(record)
```

```terminal
$ catmandu convert MARC --type XML to PNX --fix marc2pnx.fix  < ck_neu.docx
```

Result:

```xml
<record>
<header>
<identifier>990032234200402883</identifier>
</header>
<metadata>
<record>
  <control>
    <sourcerecordid>990032234200402883</sourcerecordid>
  </control>
  <display>
    <title>Albert-Renger-Patzsch, 100 photographs 1928 : travelling exhibition / Wanderausstellung / exposition itinerante von Galerie Schürmann &amp; Kicken ; Beaubourg, Paris ; Kunsthalle Bielefeld ; Neue Sammlung München = Albert Renger-Patzsch, 100 Photographien 1928 = Albert Renger-Patzsch, 100 photographies 1928 /</title>
  </display>
</record>
```

**Comment by ckrempe** [comment]
It works, thank you! By the way, there is an XML warning when using XML parser MARC::File::XML, Version 1.03 on my Debian Jessie, perl 5.20.2 (see https://github.com/LibreCat/Catmandu-MARC/issues/22):

Use of uninitialized value in concatenation (.) or string at /usr/local/share/perl/5.20.2/MARC/File/XML.pm line 397, <GEN0> chunk 3.

Seems there is no bugfix yet in MARC::File::XML 1.03

**Comment by phochste** [comment]
@ckrempe Can you provide an example XML file which gives an error?

**Comment by jorol** [comment]
@phochste  You get the warning with all MARCXML files. Bugfix is already merged <https://github.com/perl4lib/marc-perl/pull/3>, but still no new release...
