### ISSUE TITLE
missing record/control/almaid in PNX

### ISSUE THREAD

**Issue by ckrempe** [LibreCat/Catmandu-PNX#2]
MARC data from Alma contain a (new) PNX field record/control/almaid which is missing in /usr/local/share/perl/5.20.2/Catmandu/PNX.pm -> complexType name="controlType":

<xs:element name="almaid" type="xs:string" minOccurs="0"/>

If I add that line by hand it works.

**Comment by phochste** [comment]
Ok, I'll create a new release
